apiVersion: v2
name: helm-restart-pod-job
description: A Helm chart for Kubernetes
# -- This is the chart version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.1

# -- This is the version number of the application (container) being deployed.
# It is recommended to use it with quotes.
appVersion: "0.1.0"

sources:
  [
    "https://github.com/norwoodj/helm-docs/tree/master/example-charts/best-values-example",
  ]

type: application
