apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "helm-restart-pod-job.fullname" . }}
  labels:
    {{- include "helm-restart-pod-job.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  successfulJobsHistoryLimit: {{ .Values.cronJob.successfulJobsHistoryLimit }}
  schedule: {{ .Values.cronJob.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            {{- with .Values.cronJob.securityContext }}
            securityContext: {{- toYaml . | nindent 14 }}
            {{- end }}
          serviceAccountName: {{ include "helm-restart-pod-job.serviceAccountName" . }}
          restartPolicy: OnFailure